### ISSUE TITLE
Opened files aren't switched

### ISSUE THREAD

**Issue by thany** [crot4lus/project-dropdown#4]
Opened files remain as they are when switching to another project. So when switching from project A to project B, files from project A are still open, making no sense to project B.

It should rather remember opened files for each project.

**Comment by GlennTaylorDigital** [comment]
I think I understand your point, however if I'm trying to reference some code from another project but in the same Atom instance and I then switch project it would essentially remove an open tab from Project A because I'm now in Project B - or am I missing something? The idea isn't for it to be a full blooded project management tool it was simply developed for those of us who tend to have say 15 project folders active in Atom it allows you to easily jump from A to B without having to scroll to find your next project.

**Comment by ProLoser** [comment]
Does this couple well with git projects plugin?

**Comment by GlennTaylorDigital** [comment]
HI @ProLoser 

I've not actually tried it but I can't see any reason why it wouldn't. Until yesterday there was some pretty noticeable bugs that caused issues when switching projects etc but I've put some stuff in place to get rid of that.

It's not a plugin I've ever used but feel free to give it a shot and let me know if anything is amiss!

Ta
Glenn
